### PR TITLE
Adding correct support for event tracking endpoints

### PR DESCRIPTION
**Pull request by mikelkew**
The event tracking methods were all using incorrect endpoints so I've attempted to resolve that.

The api also specifies a 'delete' method for 2 of the track_event api methods. A also noticed that some of the other delete api methods were configured to use 'post' but the documentation requires 'get' for most of them.

To better handle both 'delete' requests and nested data in the params, I switched to using RestClient as a dependency instead of just Net::HTTP.

### CODE REVIEW

**Comment by ekyfauzi** [comment]
Thank you!
It will be great if you help me to write the test too.
I'll release your update soon.

**Comment by mikelkew** [comment]
Great, thank you. Hopefully you can release it as a new version soon, as we have it as a dependency within an engine - much easier if it's a public release.

I'm not an expert with tests, but I'll try to give it a go on the weekend.  :)

**Comment by ekyfauzi** [comment]
Great!

I've been release your updates in v0.2.2.
See you in the weekend :)

**Comment by ekyfauzi** [comment]
Hi @mikelkew, seems like you forget to add `require 'rest-client'` in `active-campaign-rails.rb`, so it causing error #7 issue.

But, it's okay, i can handle it and i will release new version today! 👍

**Comment by mikelkew** [comment]
Sorry about that @ekufauzi, I was testing in a project that already had rest-client loaded so I missed that, my apologies.

**Pull request merged**
